### ISSUE TITLE
Notification of new readings

### ISSUE THREAD

**Issue by jssimpson20** [Bucknell-Biol364/Biology364#3]
https://github.com/Bucknell-Biol364/Biology364/blob/50325d62b942776c51aa16764f70a7f405062dab/00-Syllabus/Biology364.2019.syllabus.tex#L180

When you add additional readings via Git, will we be notified via Git/email?

**Comment by KField-Bucknell** [comment]
That is an excellent question. I think that I can do something like that as an Issue where I @Bucknell-Biol364/2019students
