### ISSUE TITLE
pdf not available

### ISSUE THREAD

**Issue by cheyennelmoore** [Bucknell-Biol364/Biology364#8]
https://github.com/Bucknell-Biol364/Biology364/blob/572438e53bae40d8bf14efe7bd47af8992e3b3c6/02-Assignments/Project02/Project02.Rmd#L73
@KField-Bucknell I don't think this link is working properly. I used google to find the correct pdf, but wanted to give you a heads up.

**Comment by KField-Bucknell** [comment]
Thanks for pointing this out. I have now added instructions to download the form from the Nature website.
